name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone @siegrift/tsfunct
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
